title: "LaTeX Test with GitHub Pages"
markdown: kramdown
kramdown:
  math_engine: mathjax
  mathjax:
    # Use the MathJax CDN to render the LaTeX
    cdn: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
